### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by tarmolov** [dmikis/foppish#1]
Current name `braggadocio` is hard to pronounce, memorize and write. Let's rename it to something more simple.

For example, [floppish](https://www.npmjs.com/package/floppish) :)

/cc @lemmy-

**Comment by lemmy-** [comment]
swagger-client?

**Comment by dmikis** [comment]
A packet with this name already exists in the npm repo.

**Comment by lemmy-** [comment]
It's up to you. `braggadocio` sounds fun :)

**Comment by dmikis** [comment]
Done.
